version: '3.8'

services:
  catalog_db_server:
    image: postgres:14
    environment:
      POSTGRES_USER: catalog_db
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: catalog_service
    volumes:
      - ./db-data/catalog_db_server/:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    deploy:
      mode: replicated
      replicas: 1 

  order_db_server:
    image: postgres:14
    environment:
      POSTGRES_USER: order_db
      POSTGRES_PASSWORD: 78910
      POSTGRES_DB: order_service
    volumes:
      - ./db-data/order_db_server/:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    deploy:
      mode: replicated
      replicas: 1